server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: interface-api
          uri: http://localhost:8888
          predicates:
            - Path=/api/**
          filters:
            - AddRequestHeader=gali, gaLiMiFanO

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
